#include <iostream>

int main()
{
    double totalSales = .58, money = 8.6E6, totalProfit;

    totalProfit = totalSales * money;

    std::cout << "The total amount of money generated by the East Coast division will be $" << totalProfit << ".\n";

    return 0;
}


